### ISSUE TITLE
snakemake crashes when ip/port of panoptes is not correct

### ISSUE THREAD

**Issue by fgypas** [panoptes-organization/panoptes#64]
**Describe the bug**
Snakemake crashes when ip/port of panoptes is not correct

**To Reproduce**
- Install and run panoptes
- Add flag with wrong flag (e.g. --wms-monitor "http://127.0.0.1:5001")

**Expected behavior**
The correct behavior is to exit properly with a warning message

**Screenshots or logs**

> Traceback (most recent call last):
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
>     (self._dns_host, self.port), self.timeout, **extra_kw
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
>     raise err
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 61] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
>     chunked=chunked,
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/Users/foivosgypas/miniconda3/lib/python3.7/http/client.py", line 1229, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/Users/foivosgypas/miniconda3/lib/python3.7/http/client.py", line 1275, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/Users/foivosgypas/miniconda3/lib/python3.7/http/client.py", line 1224, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/Users/foivosgypas/miniconda3/lib/python3.7/http/client.py", line 1016, in _send_output
>     self.send(msg)
>   File "/Users/foivosgypas/miniconda3/lib/python3.7/http/client.py", line 956, in send
>     self.connect()
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/urllib3/connection.py", line 184, in connect
>     conn = self._new_conn()
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
>     self, "Failed to establish a new connection: %s" % e
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10d080828>: Failed to establish a new connection: [Errno 61] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
>     timeout=timeout
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
>     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5001): Max retries exceeded with url: /create_workflow (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10d080828>: Failed to establish a new connection: [Errno 61] Connection refused'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/snakemake/logging.py", line 455, in setup_logger
>     r = requests.get(wms_monitor + "/create_workflow")
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/requests/api.py", line 75, in get
>     return request('get', url, params=params, **kwargs)
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/requests/api.py", line 60, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
>     r = adapter.send(request, **kwargs)
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5001): Max retries exceeded with url: /create_workflow (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10d080828>: Failed to establish a new connection: [Errno 61] Connection refused'))
> Building DAG of jobs...
> Traceback (most recent call last):
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/snakemake/__init__.py", line 627, in snakemake
>     batch=batch,
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/snakemake/workflow.py", line 548, in execute
>     logger.info("Building DAG of jobs...")
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/snakemake/logging.py", line 157, in info
>     self.handler(dict(level="info", msg=msg, indent=indent))
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/snakemake/logging.py", line 132, in handler
>     handler(msg)
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/snakemake/logging.py", line 228, in custom_server_handler
>     server_info = {'msg': repr(msg), 'timestamp': time.asctime(), 'id': self.server["id"]}
> AttributeError: 'Logger' object has no attribute 'server'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/bin/snakemake", line 8, in <module>
>     sys.exit(main())
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/snakemake/__init__.py", line 2029, in main
>     wms_monitor=args.wms_monitor
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/snakemake/__init__.py", line 636, in snakemake
>     print_exception(ex, workflow.linemaps)
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/snakemake/exceptions.py", line 73, in print_exception
>     log_verbose_traceback(ex)
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/snakemake/exceptions.py", line 61, in log_verbose_traceback
>     logger.debug(tb)
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/snakemake/logging.py", line 163, in debug
>     self.handler(dict(level="debug", msg=msg))
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/snakemake/logging.py", line 132, in handler
>     handler(msg)
>   File "/Users/foivosgypas/Desktop/snakemake/venv_snakemake_develop/lib/python3.7/site-packages/snakemake/logging.py", line 228, in custom_server_handler
>     server_info = {'msg': repr(msg), 'timestamp': time.asctime(), 'id': self.server["id"]}
> AttributeError: 'Logger' object has no attribute 'server'

**Comment by fgypas** [comment]
This should be fixed with https://github.com/panoptes-organization/snakemake/commit/5945f33fa1bd90e904239713a62d2efb51e440fa and #67
